split:
        folds: 5

train_resnet_128:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 128
        bs: 900
        lr: 0.0001
        wd: 0.01
        mom: 0.9

train_resnet_192:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 192
        bs: 500
        lr: 0.0003
        wd: 0.01
        mom: 0.9
