split:
        folds: 5

train_lr:
        c: 1

train_resnet_128:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 128
        bs: 512
        lr: 0.001
        wd: 0.01
        mom: 0.9

train_efficientnet_128:
        epochs: 10
        arch: "efficientnet-b4"
        precision: 16
        sz: 128
        bs: 128
        lr: 0.003
        wd: 0.01
        mom: 0.9

train_resnet_192:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 192
        bs: 500
        lr: 0.0003
        wd: 0.01
        mom: 0.9
