split:
        folds: 5

train_lr:
        c: 1

train_resnet_128:
        epochs: 20
        arch: "resnet34"
        precision: 16
        sz: 128
        bs: 512
        lr: "find"
        wd: 0.01
        mom: 0.9

train_resnet_192:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 192
        bs: 500
        lr: 0.0003
        wd: 0.01
        mom: 0.9

train_resnet_256:
        epochs: 10
        arch: "resnet34"
        precision: 16
        sz: 256
        bs: 256
        lr: 0.001
        wd: 0.01
        mom: 0.9

train_efficientnet_256:
        epochs: 20
        arch: "efficientnet-b4"
        precision: 16
        sz: 256
        bs: 32
        lr: "find"
        wd: 0.01
        mom: 0.9

train_efficientnet_384:
        epochs: 15
        arch: "efficientnet-b4"
        precision: 16
        sz: 384
        bs: 16
        lr: "find"
        wd: 0.01
        mom: 0.9

train_resnest_256:
        epochs: 20
        arch: "resnest101"
        precision: 16
        sz: 256
        bs: 32
        lr: "find"
        wd: 0.01
        mom: 0.9

